
export const metadata = {
    title: "About Us",
    description: "Generated by create next app",
  };
  

export default function Layout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <main suppressHydrationWarning={true}>
                 <section className="container mx-auto">
                    {children}
                 </section>
        </main>
    );
  }